### PR TITLE
improvement: pass through options when populating images

### PR DESCRIPTION
**Pull request by jperasmus**

### CODE REVIEW

**Comment by jordanch** [comment]
There's a user on intercom asking for this, too. 👍

**Comment by jperasmus** [comment]
> There's a user on intercom asking for this, too. 👍

Are they using CF or RTDB? If RTDB, the previous SDK should handle it already.

**Comment by jordanch** [comment]
They're using RTDB. 

will [`content.get()`](https://github.com/flamelink/flamelink/blob/master/docs/content.md#get) for previous SDK populate a related media field with multiple url values, one for each image size?

**Comment by jperasmus** [comment]
No, not multiple URL values, but it will give you the URL of the image based on the `size` option you pass through. If you use `size: 'device'` it will try and calculate the best-sized image based on the device's screen size and pixel density.

**Comment by jordanch** [comment]
Thanks!

This is good. I'll feedback to the user. 

What if the query is made on the server, can `content.get()` for RTDB and CF be extended to accept an option that will return a url object with a url for every image size? This could also be beneficial on the client, for pre-fetching for example.

**Comment by jperasmus** [comment]
We can potentially look at allowing a `sizes` option that will then expose an array of `urls` for the given sizes.

With the current SDK, the other `size` options can be provided client or server-side. Only the specific `'device'` size option cannot be provided server-side, because there is no `window` object to check for the device's screen size.

**Pull request merged**
